INSERT INTO COMMANDE (REF_DE_COMMANDE,NOM,ESTPAYE)
VALUES("CMD1","Michel",0);
INSERT INTO LIGNE_COMMANDE (REF_DE_COMMANDE,TUBE_REF,TUBE_NOMBRE_DE_VOLANTS,NUMERO,PRIX_TOTAL,NOMBRE)
SELECT "CMD1", TUBE.REF, TUBE.NOMBRE_DE_VOLANTS, "1", (TUBE.PRIX * 2), 2
FROM TUBE
WHERE TUBE.REF = "A530";
INSERT INTO LIGNE_COMMANDE (REF_DE_COMMANDE,TUBE_REF,TUBE_NOMBRE_DE_VOLANTS,NUMERO,PRIX_TOTAL,NOMBRE)
SELECT "CMD1", TUBE.REF, TUBE.NOMBRE_DE_VOLANTS, "2", (TUBE.PRIX * 5), 5
FROM TUBE
WHERE TUBE.REF = "Grade 3";
INSERT INTO COMMANDE (REF_DE_COMMANDE,NOM,ESTPAYE)
VALUES("CMD2","Jacques",1);
INSERT INTO LIGNE_COMMANDE (REF_DE_COMMANDE,TUBE_REF,TUBE_NOMBRE_DE_VOLANTS,NUMERO,PRIX_TOTAL,NOMBRE)
SELECT "CMD2", TUBE.REF, TUBE.NOMBRE_DE_VOLANTS, "1", (TUBE.PRIX * 5), 5
FROM TUBE
WHERE TUBE.REF = "A530";
INSERT INTO LIGNE_COMMANDE (REF_DE_COMMANDE,TUBE_REF,TUBE_NOMBRE_DE_VOLANTS,NUMERO,PRIX_TOTAL,NOMBRE)
SELECT "CMD2", TUBE.REF, TUBE.NOMBRE_DE_VOLANTS, "2", (TUBE.PRIX * 2), 2
FROM TUBE
WHERE TUBE.REF = "Grade 3";