DROP TABLE IF EXISTS  CLIENT;
DROP TABLE IF EXISTS  COMMANDE;
DROP TABLE IF EXISTS  FABRICANT;
DROP TABLE IF EXISTS VOLANT;
DROP TABLE IF EXISTS TUBE;
DROP TABLE IF EXISTS LIGNE_COMMANDE;
DROP TABLE IF EXISTS VALIDITE;
DROP INDEX IF EXISTS I_PK_FABRICANT;
DROP INDEX IF EXISTS I_PK_COMMANDE;
DROP INDEX IF EXISTS I_FK_COMMANDE_CLIENT;
DROP INDEX IF EXISTS I_PK_VOLANT;
DROP INDEX IF EXISTS I_FK_VOLANT_FABRICANT;
DROP INDEX IF EXISTS I_PK_CLIENT;
DROP INDEX IF EXISTS I_PK_LIGNE_COMMANDE;
DROP INDEX IF EXISTS I_FK_LIGNE_COMMANDE_COMMANDE;
DROP INDEX IF EXISTS I_FK_LIGNE_COMMANDE_TUBE;
DROP INDEX IF EXISTS I_PK_TUBE;
DROP INDEX IF EXISTS I_FK_TUBE_VOLANT;
DROP INDEX IF EXISTS I_PK_VALIDITE;
CREATE TABLE IF NOT EXISTS CLIENT(
  NOM CHAR(32) PRIMARY KEY NOT NULL,
  ADRESSE VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS COMMANDE(
  REF_DE_COMMANDE VARCHAR(128) NOT NULL,
  NOM CHAR(32) NOT NULL,
  ESTPAYE BOOLEAN NOT NULL,
  PRIMARY KEY(REF_DE_COMMANDE,NOM),
  CONSTRAINT FK_COMMANDE_CLIENT
    FOREIGN KEY(NOM)
    REFERENCES CLIENT(NOM)
);
CREATE INDEX IF NOT EXISTS I_FK_COMMANDE_CLIENT ON COMMANDE (NOM);
CREATE TABLE IF NOT EXISTS FABRICANT(
  NOM VARCHAR(128) PRIMARY KEY NOT NULL,
  ADDRESSE VARCHAR(255) NOT NULL,
  CONTACT VARCHAR(128) NOT NULL,
  TELEPHONE VARCHAR(128) NOT NULL,
  EMAIL VARCHAR(128) NOT NULL
);
CREATE TABLE IF NOT EXISTS VOLANT(
  REF VARCHAR(128) PRIMARY KEY NOT NULL,
  NOM VARCHAR(128),
  MARQUE VARCHAR(128) NOT NULL,
  CLASSEMENT INTEGER NOT NULL,
  CONSTRAINT FK_VOLANT_FABRICANT
    FOREIGN KEY(NOM)
    REFERENCES FABRICANT(NOM)
);
CREATE INDEX IF NOT EXISTS I_FK_VOLANT_FABRICANT ON VOLANT (NOM);
CREATE TABLE IF NOT EXISTS TUBE(
  REF VARCHAR(128) NOT NULL,
  NOMBRE_DE_VOLANTS INTEGER NOT NULL,
  PRIX INTEGER DEFAULT NULL,
  NOMBRE_EN_STOCK CHAR(32) NOT NULL,
  IMAGE VARCHAR(255) NOT NULL,
  PRIMARY KEY(REF,NOMBRE_DE_VOLANTS),
  CONSTRAINT FK_TUBE_VOLANT
    FOREIGN KEY(REF)
    REFERENCES VOLANT(REF)
);
CREATE INDEX IF NOT EXISTS I_FK_TUBE_VOLANT ON TUBE (REF);
CREATE TABLE IF NOT EXISTS LIGNE_COMMANDE(
  REF_DE_COMMANDE VARCHAR(128) NOT NULL,
  TUBE_REF VARCHAR(128) NOT NULL,
  TUBE_NOMBRE_DE_VOLANTS INTEGER NOT NULL,
  NUMERO CHAR(32) NOT NULL,
  PRIX_TOTAL NUMERIC(5) DEFAULT NULL,
  NOMBRE INTEGER DEFAULT NULL,
  PRIMARY KEY(REF_DE_COMMANDE,TUBE_REF,TUBE_NOMBRE_DE_VOLANTS),
  CONSTRAINT FK_LIGNE_COMMANDE_COMMANDE
    FOREIGN KEY(REF_DE_COMMANDE)
    REFERENCES COMMANDE(REF_DE_COMMANDE),
  CONSTRAINT fk_LIGNE_COMMANDE_TUBE1
    FOREIGN KEY(TUBE_REF,TUBE_NOMBRE_DE_VOLANTS)
    REFERENCES TUBE(REF,NOMBRE_DE_VOLANTS)
);
CREATE INDEX IF NOT EXISTS I_FK_LIGNE_COMMANDE_COMMANDE ON LIGNE_COMMANDE (REF_DE_COMMANDE);
CREATE INDEX IF NOT EXISTS fk_LIGNE_COMMANDE_TUBE1_idx ON LIGNE_COMMANDE (TUBE_REF,TUBE_NOMBRE_DE_VOLANTS);
CREATE TABLE IF NOT EXISTS VALIDITE(
  ANNEEDEBUT INTEGER NOT NULL,
  ANNEEFIN INTEGER NOT NULL,
  VOLANT_REF VARCHAR(128) PRIMARY KEY NOT NULL,
  CONSTRAINT fk_VALIDITE_VOLANT1
    FOREIGN KEY(VOLANT_REF)
    REFERENCES VOLANT(REF)
);
CREATE INDEX IF NOT EXISTS FK_VALIDITE_VOLANT ON VALIDITE (VOLANT_REF);
INSERT INTO VOLANT (MARQUE, REF, CLASSEMENT)
VALUES ("Yorex","A530",1);
INSERT INTO TUBE (REF,NOMBRE_EN_STOCK,NOMBRE_DE_VOLANTS,PRIX,IMAGE)
VALUES ("A530",500,12,27,"as30");
INSERT INTO VOLANT (MARQUE, REF, CLASSEMENT)
VALUES ("RSL","Grade 3",3);
INSERT INTO TUBE (REF,NOMBRE_EN_STOCK,NOMBRE_DE_VOLANTS,PRIX,IMAGE)
VALUES ("Grade 3",5000,1138,17,"rslno3tourney");
INSERT INTO VOLANT (MARQUE, REF, CLASSEMENT)
VALUES ("RSL","Grade A9",3);
INSERT INTO TUBE (REF,NOMBRE_EN_STOCK,NOMBRE_DE_VOLANTS,PRIX,IMAGE)
VALUES ("GRADE A9",10000,42,14,"rsla9");
INSERT INTO VOLANT (MARQUE, REF, CLASSEMENT)
VALUES ("RSL","Grade A1",4);
INSERT INTO TUBE (REF,NOMBRE_EN_STOCK,NOMBRE_DE_VOLANTS,PRIX,IMAGE)
VALUES ("Grade A1",6000,7,21,"no1tourney");