
CREATE TABLE IF NOT EXISTS "FABRICANT"(
    "NUMERO" INTEGER(4) NOT NULL?
    "NOM" VARCHAR(20) NOT NULL,
    "ADRESSE" VARCHAR(255),
    "CONTACT" VARCHAR(128) NOT NULL,
    "TELEPHONE" VARCHAR(10) NOT NULL,
    "MAIL" VARCHAR(128)?
    CONSTRAINT "PK_FABRICANT" PRIMARY KEY("NUMERO")
);
CREATE TABLE IF NOT EXISTS "MARQUE"(
    "NUMERO" INTEGER(4) NOT NULL PRIMARY KEY,
    "NOM" VARCHAR(128) NOT NULL
    CONSTRAINT "PK_MARQUE" PRIMARY KEY("NUMERO"),
    CONSTRAINT "FK_MARQUE_FABRICANT"
        FOREIGN KEY("NUMERO")
        REFERENCES"FABRICANT"("NUMERO")
);
CREATE TABLE IF NOT EXISTS "ACHETEUR"(
    "NUMERO" INTEGER(4) NOT NULL PRIMARY KEY,
    "NOM" VARCHAR(128) NOT NULL,
    "ESTPAYER" INTEGER(1) NOT NULL,
    CONSTRAINT "PK_ACHETEUR" PRIMARY KEY("NUMERO")
);
CREATE TABLE IF NOT EXISTS "MONTANT"(
    "PRIX" INTEGER(4) NOT NULL,
    CONSTRAINT "PK_MONTANT" PRIMARY KEY("PRIX")
);
CREATE TABLE TUBE IF NOT EXISTS "TUBE"(
    "NUMERO" INTEGER(4) NOT NULL PRIMARY KEY,
    "NOM" VARCHAR(128) NOT NULL
    CONSTRAINT "PK_TUBE" PRIMARY KEY("NUMERO"),
    CONSTRAINT "FK_TUBE_CLASSEMENT"
        FOREIGN KEY("NUMERO")
        REFERENCES "CLASSEMENT"("NUMERO"),
    CONSTRAINT "FK_TUBE_MONTANT"
        FOREIGN KEY("NUMERO")
        REFERENCES "MONTANT"("PRIX")
);
CREATE TABLE IF NOT EXISTS "CLASSEMENT"(
    "NUMERO" INTEGER(4) NOT NULL PRIMARY KEY,
    "NIVEAU" INTEGER(2) NOT NULL,
    CONSTRAINT "PK_CLASSEMENT" PRIMARY KEY("NUMERO")
);